// Fileverse certificate generation
//
// GET /api/proofs/[jobId]/certificate
// Response: JSON tax certificate and, when available, a published Fileverse URL.
//
// This route always returns the raw certificate and attempts a best-effort
// publish through the internal /api/fileverse/publish endpoint.

import { NextRequest, NextResponse } from "next/server";
import { jobStore } from "@/lib/job-store";

function certificateMarkdown(certificate: {
  version: string;
  issuer: string;
  issued_at: string;
  job_id: string;
  ledger_commitment: string;
  total_tax_paisa: string;
  user_type_code: number;
  used_44ada: number;
  starknet_tx_hash: string;
  proof_type: string;
}): string {
  return `# ProofOS Tax Certificate

**Issuer:** ${certificate.issuer}
**Issued At:** ${certificate.issued_at}
**Certificate Version:** ${certificate.version}

---

## Proof Metadata

- **Job ID:** \`${certificate.job_id}\`
- **Proof Type:** ${certificate.proof_type}
- **Starknet TX Hash:** \`${certificate.starknet_tx_hash}\`
- **Ledger Commitment:** \`${certificate.ledger_commitment}\`

---

## Tax Metadata

- **Total Tax (Paisa):** ${certificate.total_tax_paisa}
- **User Type Code:** ${certificate.user_type_code}
- **Used Section 44ADA:** ${certificate.used_44ada === 1 ? "Yes" : "No"}

---

Generated by ProofOS. This certificate confirms the referenced tax computation and STARK verification event.
`;
}

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ jobId: string }> }
) {
  const { jobId } = await params;
  const store = jobStore;
  const fallbackTxHash = req.nextUrl.searchParams.get("txHash");
  const job = store.get(jobId) ?? (fallbackTxHash ? store.findByStarknetTxHash(fallbackTxHash) : undefined);

  if (!job) {
    return NextResponse.json({ error: "Job not found" }, { status: 404 });
  }

  if (job.status !== "done" || !job.result) {
    return NextResponse.json(
      { error: "Certificate not yet available", status: job.status },
      { status: 202 }
    );
  }

  const { result } = job;

  // Build the certificate document
  const certificate = {
    version: "1.0",
    issuer: "ProofOS",
    issued_at: new Date().toISOString(),
    job_id: jobId,
    ledger_commitment: result.ledger_commitment,
    total_tax_paisa: result.total_tax_paisa,
    user_type_code: result.user_type_code,
    used_44ada: result.used_44ada ? 1 : 0,
    starknet_tx_hash: result.starknet_tx_hash,
    proof_type: "STARK via Starknet",
    note: "This certificate was generated by ProofOS. The tax calculation was verified on Starknet as a STARK proof. The ledger commitment is a SHA-256 hash of the canonical serialized transaction ledger.",
  };
  const markdown = certificateMarkdown(certificate);

  // Best-effort publish to Fileverse through internal API.
  try {
    const publishUrl = new URL("/api/fileverse/publish", req.url);
    const res = await fetch(publishUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title: `ProofOS Tax Certificate - ${jobId.slice(0, 8)}`,
        markdownContent: markdown,
      }),
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({ error: "Fileverse publish failed" }));
      console.warn("Fileverse publish unavailable:", err.error ?? res.statusText);
      return NextResponse.json({ certificate, markdown });
    }

    const fileverseDoc = await res.json();
    return NextResponse.json({
      certificate,
      markdown,
      fileverse_url: fileverseDoc?.url ?? null,
      fileverse_ipfs_hash: fileverseDoc?.ipfsHash ?? null,
    });
  } catch (err) {
    console.error("Fileverse publish error:", err);
    return NextResponse.json({ certificate, markdown });
  }
}
