export interface FileverseReportInput {
  title: string;
  markdownContent: string;
}

export interface FileverseResult {
  success: boolean;
  url?: string;
  ipfsHash?: string;
  error?: string;
}

export async function publishToFileverse(input: FileverseReportInput): Promise<FileverseResult> {
  try {
    const res = await fetch("/api/fileverse/publish", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(input),
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({ error: "Unknown error" }));
      return { success: false, error: err.error ?? `HTTP ${res.status}` };
    }

    const data = await res.json();
    return { success: true, url: data.url, ipfsHash: data.ipfsHash };
  } catch (err) {
    return {
      success: false,
      error: err instanceof Error ? err.message : "Network error",
    };
  }
}

export function buildTaxReportMarkdown(input: {
  breakdown: Record<string, string>;
  userType: string;
  use44ada: boolean;
  wallets: string[];
  proofTxHash?: string;
  ledgerCommitment?: string;
  generatedAt?: number;
}): string {
  const { breakdown, userType, use44ada, wallets, proofTxHash, ledgerCommitment } = input;
  const date = new Date(input.generatedAt ?? Date.now()).toLocaleDateString("en-IN", {
    day: "2-digit", month: "long", year: "numeric",
  });

  const inr = (v: string) => {
    const n = parseFloat(v ?? "0");
    return isNaN(n)
      ? "INR 0.00"
      : n.toLocaleString("en-IN", { style: "currency", currency: "INR", minimumFractionDigits: 2 });
  };

  const vdaGross = breakdown.vda_gains_gross_inr ?? breakdown.vda_gains_inr ?? "0";

  return `# ProofOS - Indian Crypto Tax Report

**Generated:** ${date}
**Financial Year:** FY 2025-26 (AY 2026-27)
**Tax Regime:** New Regime (Section 115BAC)

---

## Taxpayer Information

| Field | Value |
|---|---|
| Entity Type | ${userType === "individual" ? "Individual" : userType === "huf" ? "HUF" : "Corporate"} |
| Section 44ADA | ${use44ada ? "Applied (50% presumptive)" : "Not applied"} |
${wallets
  .slice(0, 3)
  .map((w, i) => `| Wallet ${i + 1} | \`${w.slice(0, 10)}...${w.slice(-8)}\` |`)
  .join("\n")}

---

## Professional Income

| Description | Amount |
|---|---|
| Gross Professional Income | ${inr(breakdown.professional_income_inr)} |
${parseFloat(breakdown.standard_deduction_inr ?? "0") > 0 ? `| Standard Deduction (Sec 16) | (${inr(breakdown.standard_deduction_inr)}) |\n` : ""}${use44ada ? `| Taxable Income after 44ADA | ${inr(breakdown.taxable_professional_income_inr)} |\n` : ""}| Slab Tax | ${inr(breakdown.professional_tax_inr)} |
${parseFloat(breakdown.surcharge_inr ?? "0") > 0 ? `| Surcharge | ${inr(breakdown.surcharge_inr)} |\n` : ""}${parseFloat(breakdown.section_87a_rebate_inr ?? "0") > 0 ? `| Section 87A Rebate | (${inr(breakdown.section_87a_rebate_inr)}) |\n` : ""}

---

## Virtual Digital Assets (Section 115BBH)

| Description | Amount |
|---|---|
| Gross VDA Gains | ${inr(vdaGross)} |
${parseFloat(breakdown.fees_as_coa_inr ?? "0") > 0 ? `| Gas Fees (COA) | (${inr(breakdown.fees_as_coa_inr)}) |\n` : ""}| VDA Tax @ 30% | ${inr(breakdown.vda_tax_inr)} |
| VDA Losses (non-deductible) | ${inr(breakdown.vda_losses_inr)} |

---

## Tax Summary

| Description | Amount |
|---|---|
| Total Tax Before Cess | ${inr((parseFloat(breakdown.professional_tax_inr ?? "0") + parseFloat(breakdown.vda_tax_inr ?? "0")).toString())} |
| Health & Education Cess (4%) | ${inr(breakdown.cess_inr)} |
| **Total Tax Liability** | **${inr(breakdown.total_tax_inr)}** |
${parseFloat(breakdown.tds_194s_credit_inr ?? "0") > 0 ? `| TDS Credit (Sec 194S) | (${inr(breakdown.tds_194s_credit_inr)}) |\n| **Tax Payable After TDS** | **${inr(breakdown.tax_payable_after_tds_inr ?? breakdown.total_tax_inr)}** |` : ""}

---

${proofTxHash ? `## ZK Proof (STARK via Starknet)

- **Starknet TX:** \`${proofTxHash}\`
${ledgerCommitment ? `- **Ledger Commitment:** \`${ledgerCommitment}\`` : ""}
- **Explorer:** https://sepolia.starkscan.co/tx/${proofTxHash}

---

` : ""}> *This report is generated by ProofOS for informational purposes only. Consult a qualified CA before filing your ITR. Calculations per Indian IT Act for FY 2025-26 under the new tax regime.*
`;
}
